tasks:
  - before: |
      python3 -m venv /workspace/gitpodissue/venv
      source /workspace/gitpodissue/venv/bin/activate
      echo "source /workspace/gitpodissue/venv/bin/activate" >> ~/.bashrc
      pip install pyspark
image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
